### ISSUE TITLE
UDSCommand missing services

### ISSUE THREAD

**Issue by camercu** [rnd-ash/ecu_diagnostics#14]
Going based off [Wikipedia](https://en.wikipedia.org/wiki/Unified_Diagnostic_Services#Services) (again, sorry I don't have access to the official standard), it appears the [UDSCommand enum](https://github.com/rnd-ash/ecu_diagnostics/blob/0bfbd5916b068faa1ef8b9b7a6a6cc28490ab203/src/uds/mod.rs#L42) is missing SID 0x29 (Authentication) and 0x38 (Request File Transfer). If you have access to the standard, can you please check it to see if these are actually missing standard services?

**Comment by camercu** [comment]
[This blog post](https://shayanmukhtar.com/2020/10/26/uds-protocol/) suggests that the Service IDs I mentioned are part of the newest (2020) revision to the UDS standard.

**Comment by nyurik** [comment]
@camercu I fixed this as part of the v0.4.1 of the [auto_uds crate](https://github.com/nyurik/auto_uds). ECU diagnostics now uses it too.

**Comment by nyurik** [comment]
I think this can now be closed

**Comment by rnd-ash** [comment]
Agreed!
