### ISSUE TITLE
the project does not compile

### ISSUE THREAD

**Issue by carik-car** [rnd-ash/ecu_diagnostics#2]
this language is new to me, build error is -

`warning: unused imports: `BorrowMut`, `Borrow`, `LockResult`, `cell::RefCell`, `convert::TryInto`, `default`
  --> src\hardware\passthru\mod.rs:22:14
   |
22 |     borrow::{Borrow, BorrowMut},
   |              ^^^^^^  ^^^^^^^^^
23 |     cell::RefCell,
   |     ^^^^^^^^^^^^^
24 |     convert::TryInto,
   |     ^^^^^^^^^^^^^^^^
25 |     default,
   |     ^^^^^^^
26 |     ffi::c_void,
27 |     sync::{Arc, LockResult, Mutex, PoisonError},
   |                 ^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `RegValue`
  --> src\hardware\passthru\mod.rs:35:22
   |
35 | use winreg::{RegKey, RegValue};
   |                      ^^^^^^^^

warning: unused import: `RwLock`
 --> src\hardware\passthru\lib_funcs.rs:5:22
  |
5 | use std::sync::{Arc, RwLock};
  |                      ^^^^^^

warning: unused import: `winreg::enums::*`
 --> src\hardware\passthru\lib_funcs.rs:9:5
  |
9 | use winreg::enums::*;
  |     ^^^^^^^^^^^^^^^^

warning: unused imports: `RegKey`, `RegValue`
  --> src\hardware\passthru\lib_funcs.rs:12:14
   |
12 | use winreg::{RegKey, RegValue};
   |              ^^^^^^  ^^^^^^^^

warning: unused variable: `x`
   --> src\hardware\passthru\mod.rs:811:13
    |
811 |     fn from(x: PoisonError<T>) -> Self {
    |             ^ help: if this is intentional, prefix it with an underscore: `_x`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `x`
   --> src\hardware\passthru\mod.rs:820:13
    |
820 |     fn from(x: PoisonError<T>) -> Self {
    |             ^ help: if this is intentional, prefix it with an underscore: `_x`

warning: variable does not need to be mutable
  --> src\kwp2000\read_dtc_by_status.rs:90:9
   |
90 |     let mut res: Vec<DTC> = Vec::new();
   |         ----^^^
   |         |
   |         help: remove this `mut`
   |
   = note: `#[warn(unused_mut)]` on by default

warning: associated function is never used: `get_version`
   --> src\hardware\passthru\lib_funcs.rs:291:12
    |
291 |     pub fn get_version(&self, dev_id: u32) -> PassthruResult<DrvVersion> {
    |            ^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

warning: associated function is never used: `stop_msg_filter`
   --> src\hardware\passthru\lib_funcs.rs:439:12
    |
439 |     pub fn stop_msg_filter(&self, channel_id: u32, filter_id: u32) -> PassthruResult<()> {
    |            ^^^^^^^^^^^^^^^

warning: unused `Result` that must be used
   --> src\hardware\passthru\mod.rs:464:17
    |
464 |                 self.close();
    |                 ^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_must_use)]` on by default
    = note: this `Result` may be an `Err` variant, which should be handled

warning: unused `Result` that must be used
   --> src\hardware\passthru\mod.rs:636:17
    |
636 |                 self.close();
    |                 ^^^^^^^^^^^^^
    |
    = note: this `Result` may be an `Err` variant, which should be handled

warning: 12 warnings emitted`

**Comment by rnd-ash** [comment]
Closing this issue. It does compile. These are just warnings and can be ignored. Based on your own output the compiler did not output any ERRORs.
