### ISSUE TITLE
Hardware support

### ISSUE THREAD

**Issue by tayler-king** [rnd-ash/ecu_diagnostics#3]
I'm assuming this currently only supports the Macchina A0/M2 for OSX/Linux usage?

The M2 seems to be out of stock everywhere unfortunately which makes using this library a bit difficult.

**Comment by rnd-ash** [comment]
Yes that is correct. J2534 is mainly a Windows API, and I unofficially ported it for the A0/M2 to Linux+OSX. 

If you have a socketcan adapter, you can use that with Linux though!

**Comment by tayler-king** [comment]
> Yes that is correct. J2534 is mainly a Windows API, and I unofficially ported it for the A0/M2 to Linux+OSX. 
> 
> 
> 
> If you have a socketcan adapter, you can use that with Linux though!

Looking through OVD, it seems like any J2534 supported device should work under Windows with an appropriate driver? Such as with the Openport 2.0: https://www.tactrix.com/index.php?Itemid=61

**Comment by rnd-ash** [comment]
Correct
